add: upload library scrapper
rekyungmin/biblebot-scraper pull request #1
Opened 2020-10-28 09:02 UTC by yongki150

여러 모듈들을 제가 이해한 부분만 커스텀한 버전을 따로 만들어 사용해보려 했지만 이미 짜여진 코드를 바꾸기가 쉽지않았습니다. 이 부분은 아예 제가 클론코딩으로 따로 분석하고있습니다.

일단 모듈을 그대로 사용해서 도서관 스크래퍼에 적용해보았습니다.

2020-10-28 09:38 UTC, rekyungmin commented
[black](https://github.com/psf/black) 을 사용해서 코드 포매팅을 맞춰주세요~

2020-10-28 09:39 UTC, rekyungmin commented on biblebot/api/lib.py
> +from biblebot.exceptions import ParsingError
다른 코드에서 전부 상대경로를 사용하고 있어서, 여기서도 상대경로로 변경해주시면 좋을 듯 합니다.

2020-10-28 13:50 UTC, yongki150 commented on biblebot/api/lib.py
> +from biblebot.exceptions import ParsingError
넵 수정하였습니다!

2020-10-28 13:52 UTC, yongki150 commented
`black`설치한후 해당 파일에 적용하였습니다
`precondition`부분은 내일 적용하고 올리겠습니다.

2020-10-29 11:34 UTC, yongki150 commented
`precondition`을 적용만 해본 상태라 실제 작동이 되는지 내일 책을 반납해보고 결과를 한번 확인해보겠습니다.

2020-10-30 14:27 UTC, yongki150 commented
질문있습니다!
`precondition`을 통해 parsing을 할 수 있는 페이지인지 검사를 할 수 있는 것같습니다.
근데 도서관에서 연체목록을 볼 수 있는 /Mylibrary 페이지는 로그인이 풀리면 `alert`창없이 그냥 바로 로그인창으로 가는 것같습니다.
도서관용만의 `precondition`을 만들어야겠다 생각하였습니다.
`status`가 302면 `errorData`형식으로 리턴해주는 식으로 바꿔보려고 합니다. 이런 방식으로 변경은 어떻게 보시나요?

2020-10-31 08:12 UTC, rekyungmin commented
> 질문있습니다!
> `precondition`을 통해 parsing을 할 수 있는 페이지인지 검사를 할 수 있는 것같습니다.
> 근데 도서관에서 연체목록을 볼 수 있는 /Mylibrary 페이지는 로그인이 풀리면 `alert`창없이 그냥 바로 로그인창으로 가는 것같습니다.
> 도서관용만의 `precondition`을 만들어야겠다 생각하였습니다.
> `status`가 302면 `errorData`형식으로 리턴해주는 식으로 바꿔보려고 합니다. 이런 방식으로 변경은 어떻게 보시나요?
> 
> 일단 내일 구현은 해놓아보겠습니다.

세션이 발급되지 않았거나, 세션이 만료된 상황에서의 HTTP status code, header, body 등을 참고하여 사전조건을 체크해주는 것이 좋습니다. 302 는 애매한 status code 이기는 하지만, 여러 상황에서 문제가 없다고 판단되면 적용해도 좋습니다.

`IParserPrecondition` 을 상속하는 클래스를 만들면 사전조건을 체크합니다. [여기](https://github.com/rekyungmin/biblebot-scraper/blob/9a7c732ad9f82bc0a28b0f2f5548dc504a02fec7/biblebot/api/lms.py#L49)를 참고해서 진행하면 됩니다.

2020-10-31 08:13 UTC, rekyungmin commented
그리고 `Login` 클래스가 없네요. Library 클래스를 이용하기 위해서는 로그인이 필요하지 않나요?

2020-11-01 07:55 UTC, yongki150 commented
**[질문]** 도서관만의 `IParserPrecondition`을 상속하는 `_SessionExpiredChecker`클래스를 만들었습니다.
앞서 말한 것처럼 도서관 마이페이지는 세션이 만료될때, `alert`창 없이 메인페이지로 리다이렉트 되어서 이를 이용한 부분입니다.
여기서, 문제점은 도서관만이 아닌 다른 `ParserPrecondition`이 적용된 클래스들도 도서관만의 `_SessionExpiredChecker`를 검사한다는 점입니다. 
아직까지 도서관을 제외한 다른곳에서 세션이 만료될때, 리다이렉트되는 곳은 없어서 문제점은 보이지 않지만 만약 이를 해결해야한다면
`IParserPrecondition` 이 아닌 다른 인터페이스를 만들어 상속하는 방법을 사용하면 되나요?

**[도서관 Login클래스에서 추가한 부분]** `Login`클래스의 `fetch_main_page`는 로그인이 된 메인페이지를 크롤링하는 부분입니다.
로그인이 된 메인페이지에는 본인의 이름이 나와있어서 로그인 확인용으로나 프론트단에서 컨텐츠로 사용할 수 있을수 있어서 만들어보았습니다.

>아래 코드는 biblebot-server 에서 Login 라우트(?)에서 biblebot-scraper의 Login클래스를 돌려본 결과값입니다.
```
ResourceData(data={'cookies': {'ASP.NET_SessionId': 'ieceu41unxgthdrfocpkbulu'}, 
'validate-content': '김용기님!', 
'iat': 1604214709}, 
link='http://lib.bible.ac.kr', meta={})
```

2020-11-01 07:55 UTC, yongki150 commented
> 그리고 `Login` 클래스가 없네요. Library 클래스를 이용하기 위해서는 로그인이 필요하지 않나요?

넵 추가하였습니다!

2020-12-05 07:23 UTC, rekyungmin commented
https://github.com/rekyungmin/biblebot-scraper/blob/master/biblebot/api/__init__.py
https://github.com/rekyungmin/biblebot-scraper/blob/master/biblebot/__init__.py

여기에 API 접근 포인트를 추가해주세요~

2020-12-14 06:34 UTC, yongki150 commented
늦어서 죄송합니다! 접근 포인트 추가하였습니다.

2020-12-15 07:03 UTC, yongki150 commented
### 연체도서의 이미지도 데이터로 추가하였습니다.
> 별도의 추천도서 이미지 스크래퍼 클래스까지 추가되면 
경진대회 이후 보완하고자 하는 도서관 스크래퍼 기능은 완료됩니다.

### 특징
190행의 `BookPhoto`클래스의 `parse`메서드에 `precondition`기능이 없는 이유는
로그인이 필요없는 `url`의 데이터를 가져오기 때문입니다.

### 결과값

```
ResourceData("data="{
   "head":[
      "No",
      "서지정보",
      "대출일자",
      "반납예정일",
      "대출상태",
      "연기신청",
      "도서URL"
   ],
   "body":[
      [
         "1",
         " 4차 산업혁명과 그리스도인의 삶",
         "2020-11-27",
         "2020-12-17",
         "대출중",
         "연기불가",
         "해당없음",
         {
            "width":82,
            "height":122,
            "format":"JPEG",
            "img":"/9j/4AAQSkZJRgABAQAAAQABAAD/...."
         }
      ],
      [
         "2",
         " 여자 20대, 10년 후 명함을 준비하라",
         "2020-11-26",
         "2020-12-17",
         "대출중",
         "연기불가",
         "해당없음",
         "이미지를 불러올 수 없습니다."
      ]
   ]
},
"link=""https://lib.bible.ac.kr/MyLibrary",
"meta="{
   
})
```

2020-12-16 16:53 UTC, rekyungmin requested changes
모듈 이름은 lib 대신 library로 풀네임으로 가는게 어떤가요?

다음 주에 만나서 테스트 코드 확인하고 머지할게요~

2020-12-16 16:53 UTC, rekyungmin commented on biblebot/api/lib.py
> +        if bool(re.match(r"https?://", img_url)):
bool 이 필요한가요?

2020-12-16 16:53 UTC, rekyungmin commented on biblebot/api/lib.py
> +        if li == 'HOME':
black 적용해주세요~

2020-12-21 18:34 UTC, yongki150 commented on biblebot/api/lib.py
> +        if li == 'HOME':
넵 적용하였습니다!

2020-12-21 18:38 UTC, yongki150 commented on biblebot/api/lib.py
> +        if bool(re.match(r"https?://", img_url)):
따로 bool 메서드를 감싸줄 필요가 없었군요! 수정하였습니다

2020-12-29 07:48 UTC, yongki150 commented
### 첨삭 반영 내용
1. `Number`데이터를  `ISBN`데이터로 수정
2. 이미지 없을시 `None`으로 처리
3. `BookPhoto`클래스의 기능을 명확화

2020-12-29 08:08 UTC, rekyungmin commented on biblebot/api/library.py
> +        )
fetch_detail과 fetch는 각각 무슨 역할인가요?

2020-12-29 08:08 UTC, rekyungmin commented on biblebot/api/library.py
> +    async def fetch(
parse가 필요없는데 BookPhoto가 있어야하는 이유가 있나요?

2020-12-29 08:26 UTC, yongki150 commented on biblebot/api/library.py
> +        )
`fetch`메서드는 연체목록 페이지를 `fetch`합니다.
`서지정보`, `대출일자`, `반납예정일`, `대출상태`, `연기신청`의 데이터와
`상세목록 페이지로 가는 URL`의 데이터가 있는 페이지입니다.
쿠키가 필요합니다.

`fetch_detail`메서드는 상세목록 페이지를 `fetch`합니다.
 `ISBN`데이터와 `이미지 바이트 코드를 받는 URL`의 데이터가 있는 페이지입니다.
세션유지가 필요없는 페이지라 인자로 쿠키가 필요없습니다.

다시보니 상세페이지를 다루는 클래스를 따로 만드는것이 더 나은것 같습니다.
수정해보도록하겠습니다.

2020-12-29 08:28 UTC, yongki150 commented on biblebot/api/library.py
> +    async def fetch(
ResourceData 형식으로 반환해주는 parse 메서드가 빠진것같습니다.
수정해놓겠습니다.

2020-12-31 08:24 UTC, yongki150 commented on biblebot/api/library.py
> +    async def fetch(
`BookPhoto` 클래스의 `parse` 메소드에 
`parse`에 실패한 조건이 없는 이유는 

>  **참고자료** 
`intranet` 스크래퍼의 `StudentPhoto` 클래스의 `parse` 메소드
```
else: 
      return ErrorData(error={"title": "이미지를 불러올 수 없습니다."}, link=response.url)
```

서버코드에서
위와 같은 조건을 두어 에러를 리턴하여 중단하지 않고
`None`으로 처리하여 그대로 api의 결과 데이터를 출력하기 때문입니다.

2020-12-31 08:25 UTC, yongki150 commented on biblebot/api/library.py
> +        )
클래스 분리하였습니다!

2021-01-05 10:28 UTC, rekyungmin requested changes
로그인 클래스 리뷰 마쳤습니다.

2021-01-05 10:28 UTC, rekyungmin commented on biblebot/api/library.py
> +    ) -> Response:
이 함수가 필요한 이유가 뭔가요??

2021-01-05 10:28 UTC, rekyungmin commented on biblebot/api/library.py
> +    def parse(cls, response: Response, cookies: Dict[str, str]) -> APIResponseType:
함수 시그니처가 추상 클래스에 정의된 내용과 달라요. cookies 정보는 response 객체 안에 존재할텐데 별도의 cookies 파라미터가 왜 필요한가요?

2021-01-05 10:28 UTC, rekyungmin commented on biblebot/api/library.py
> +    def parse(cls, response: Response, cookies: Dict[str, str]) -> APIResponseType:
parse 함수에서 에러 발생해요

2021-01-05 10:59 UTC, yongki150 commented on biblebot/api/library.py
> +    ) -> Response:
로그인을 판별하는 부분입니다.
도서관 홈페이지에 나타나는 이름의 유무에 따라 확인할 수 있습니다.
아래 첨삭해주신 부분에 추상클래스를 해치는 요인이 되니 다른 대안을 생각해서 수정해놓겠습니다.

2021-01-05 11:03 UTC, yongki150 commented on biblebot/api/library.py
> +    def parse(cls, response: Response, cookies: Dict[str, str]) -> APIResponseType:
연체목록이 없을때 `ParsingError`가 일어납니다. 서버코드에서 해당 에러를 잡아주는 미들웨어가 있어서 연체목록이 없을 경우에 대한 에러를 처리해주었다고 생각했습니다.

2021-01-06 08:49 UTC, yongki150 commented
1. `Login`클래스의 불필요한 `fetch_main_page`메서드를 삭제하였습니다. 
2. `Login`클래스의 (1)잘못된입력 (2)인코딩오류 및 경로입력 오류에 대한 오류 처리 하였습니다.
> 인코딩 및 경로입력 오류 모두 `location`헤더에서 ErrorCode 404 에 대한 공통점을 가지고 있습니다.
이를 처리할 때 사용자 입장에서는 인코딩에 대한 어구가 어려울것 같아서 제외하였고,
잘못된 경로임을 알리는 메세지로 알리도록 처리하였습니다.

3. 1월 9일까지 연체때문에 대출 제한이 걸려있어서 
실제 대출목록 있는경우에 대한 수정은 그 제한이 풀리는 다음주에 해놓겠습니다.

2021-01-06 09:05 UTC, yongki150 commented
질문있습니다.
`Login`클래스의 `fetch` 메소드 부분입니다.

**A: 로그인이 정상적으로 이루어진 상황**
```
form = {
            "l_id": b64encode(user_id.encode()).decode(),
            "l_pass": b64encode(user_pw.encode()).decode(),
        }
       return await HTTPClient.connector.post(
            cls.URL, headers=headers, body=form, timeout=timeout, **kwargs
        )
```
**B: 로그인이 이루어지지 않은 상황
`fetch`했을시 `cookie` 헤더가 없고, `location`헤더에서 `404에러`라고 알려줌**
```
form = {
            "l_id": user_id,
            "l_pass": user_pw,
        }
        return await HTTPClient.connector.post(
            cls.URL, headers=headers, body=form, timeout=timeout, **kwargs
        )
```

A 상황에서 b64인코딩후 디코딩을 한상태로 보내는형태가
B 상황과 같다고 생각했습니다.
근데 결과는 다른 점이 궁금합니다.

2021-01-06 13:19 UTC, rekyungmin commented
> **질문있습니다.**
> `Login`클래스의 `fetch` 메소드 부분입니다.
> 
> **A: 로그인이 정상적으로 이루어진 상황**
> 
> ```
> form = {
>             "l_id": b64encode(user_id.encode()).decode(),
>             "l_pass": b64encode(user_pw.encode()).decode(),
>         }
>        return await HTTPClient.connector.post(
>             cls.URL, headers=headers, body=form, timeout=timeout, **kwargs
>         )
> ```
> 
> **B: 로그인이 이루어지지 않은 상황 `fetch`했을시 `cookie` 헤더가 없고, `location`헤더에서 `404에러`라고 알려줌**
> 
> ```
> form = {
>             "l_id": user_id,
>             "l_pass": user_pw,
>         }
>         return await HTTPClient.connector.post(
>             cls.URL, headers=headers, body=form, timeout=timeout, **kwargs
>         )
> ```
> 
> A 상황에서 b64인코딩후 디코딩을 한상태로 보내는형태가
> B 상황과 같다고 생각했습니다.
> 근데 결과는 다른 점이 궁금합니다.

A는 base64 인코딩된 문자열이고, B는 원본 문자열이네요.
b64encode 의 첫번째 파라미터 타입은 byte-like 객체이고 리턴 타입은 bytes 객체입니다.
따라서 user_id를 encode() 하여 bytes 객체로 변환하여 넘긴 거고, 
리턴 타입은 bytes이니 decode() 해서 문자열로 바꾼겁니다.

2021-01-07 05:36 UTC, yongki150 commented
아하! `bytes객체`를 다루군요.
저는 A상황에서 인코딩, 디코딩하면 결국 다시 `user_id `원문으로 돌아오는 줄 알았습니다.
```
>>> b64encode("ygflove95".encode()).decode()
'eWdmbG92ZTk1'
```
파이썬 콘솔에 돌려보니 이렇게 변환이 되는 거였군요.
감사합니다!

2021-01-11 08:19 UTC, yongki150 commented
https://github.com/rekyungmin/biblebot-scraper/pull/1#issuecomment-755169039
위 코멘트의 4번까지 완료하였습니다!

2021-01-11 13:38 UTC, rekyungmin commented
수고하셨습니다. 머지하고 PyPI 에 배포할게요.
추가로, [API 문서](https://github.com/rekyungmin/biblebot-scraper/blob/master/docs/APIs.md
)에 Library 를 추가하면 좋을 듯 합니다~

2021-01-11 13:39 UTC, merged

2021-01-11 13:55 UTC, yongki150 commented
오오 감사합니다!!! API문서에 내일 추가해놓겠습니다